# docker-compose practica integradora Grupo 1
version: "3.8"
services:
  productos:
    container_name: contiene_vue
    build: productos/
    image: pi_front
    # Quitar antes de entregar
    volumes:
      - ./productos:/app
    #
    networks:
      red_integradora:
        ipv4_address: 172.19.0.18

  produccion:
    container_name: contiene_apache
    image: zarritas/imagen-apache2
    depends_on:
      - database_productos
      - database_tienda
    networks:
      red_integradora:
        ipv4_address: 172.19.0.4

  tienda:
    container_name: contiene_tomcat
    image: zarritas/imagen-tomcat
    depends_on:
      - database_tienda
      - database_productos
#    volumes:
#      - ./tienda/build/libs:/usr/local/tomcat/webapps
    networks:
      red_integradora:
        ipv4_address: 172.19.0.3

  database_tienda:
    container_name: contiene_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
    networks:
      red_integradora:
        ipv4_address: 172.19.0.2

  database_productos:
    container_name: contiene_mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      red_integradora:
        ipv4_address: 172.19.0.5

networks:
  red_integradora:
    name: red_integradora
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
