# docker-compose practica integradora Grupo 1
version: "5"
services:
  productos:
    container_name: contiene_vue
    build: productos/
    image: node_desarrollo
    # Quitar antes de entregar
    volumes:
      - ./productos:/app
    #
    networks:
      red_integradora:
        ipv4_address: 172.19.0.18

  produccion:
    container_name: contiene_apache
    image: zarritas/imagen_apache2
    restart: always
    networks:
      red_integradora:
        ipv4_address: 172.19.0.4

  tienda:
    container_name: contiene_tomcat
    image: zarritas/imagen_tomcat
    restart: always
#    volumes:
#      - ./tienda/build/libs:/usr/local/tomcat/webapps
    networks:
      red_integradora:
        ipv4_address: 172.19.0.3
    command: ["./wait-for-it.sh", "172.19.0.2:3306", "-t", "0","--","catalina.sh","run"]

  database_tienda:
    container_name: contiene_mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    networks:
      red_integradora:
        ipv4_address: 172.19.0.2

  database_productos:
    container_name: contiene_mongo
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      red_integradora:
        ipv4_address: 172.19.0.5

networks:
  red_integradora:
    name: red_integradora
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
