name: Deploy Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub with PAT
      run: echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Create ./dist and build productos
      run: |
        cd productos
        npm install
        npm run build
        cd ..

    - name: Crear libs
      run: |
        cd tienda
        chmod +x gradlew
        ./gradlew bootWAR
        cd ..
    
    - name: Build and push Docker images
      run: |
        docker buildx build --push --tag zarritas/imagen_productos:latest ./productos
        docker buildx build --push --tag zarritas/imagen_tomcat:latest ./tienda
        docker buildx build --push --tag zarritas/imagen_bind9:latest ./Bind9

    - name: Run Docker Compose
      run: docker-compose -f docker-compose.yml up -d
