name: Deploy Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Build and push Docker images
      run: |
        docker buildx build --push --tag zarritas/imagen_productos:latest ./productos
        docker buildx build --push --tag zarritas/imagen_tomcat:latest ./tienda
        docker buildx build --push --tag zarritas/imagen_bind9:latest ./Bind9

    - name: Run Docker Compose
      run: docker-compose -f docker-compose.yml up -d
